/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab3.paradigmas.HuacchaMachuca;


import java.util.ArrayList;
import javax.swing.JOptionPane;

public class App {

    public static void main(String[] args) {
          
    }
    
    private static ArrayList<String> listaDinamica(){
        ArrayList<String> lista=new ArrayList();
        char respuesta;
        do{
            lista.add(JOptionPane.showInputDialog("Ingresar key"));
            respuesta=JOptionPane.showInputDialog("Ingresar mas keys: S/N").charAt(0);
        }while(respuesta=='s' || respuesta =='S');
        return lista;
    }
   
}
